<?php

/**
 * Basemeta_tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $module
 * @property integer $parent_id
 * @property string $title
 * @property string $description
 * @property string $key_words
 * 
 * @method string   getModule()      Returns the current record's "module" value
 * @method integer  getParentId()    Returns the current record's "parent_id" value
 * @method string   getTitle()       Returns the current record's "title" value
 * @method string   getDescription() Returns the current record's "description" value
 * @method string   getKeyWords()    Returns the current record's "key_words" value
 * @method meta_tag setModule()      Sets the current record's "module" value
 * @method meta_tag setParentId()    Sets the current record's "parent_id" value
 * @method meta_tag setTitle()       Sets the current record's "title" value
 * @method meta_tag setDescription() Sets the current record's "description" value
 * @method meta_tag setKeyWords()    Sets the current record's "key_words" value
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemeta_tag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('meta_tag');
        $this->hasColumn('module', 'string', 64, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 64,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('key_words', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
              2 => 'key_words',
             ),
             ));
        $this->actAs($i18n0);
    }
}