<?php

/**
 * Baseattribute_type
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $attribute_def
 * @property Doctrine_Collection $attribute_value
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getAttributeDef()    Returns the current record's "attribute_def" collection
 * @method Doctrine_Collection getAttributeValue()  Returns the current record's "attribute_value" collection
 * @method attribute_type      setName()            Sets the current record's "name" value
 * @method attribute_type      setAttributeDef()    Sets the current record's "attribute_def" collection
 * @method attribute_type      setAttributeValue()  Sets the current record's "attribute_value" collection
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseattribute_type extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attribute_type');
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('attribute_def', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('attribute_value', array(
             'local' => 'id',
             'foreign' => 'attribute_type_id'));
    }
}