<?php

/**
 * Baseattribute_def_value
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $attribute_def_id
 * @property string $value
 * @property attribute_def $attribute_def
 * @property Doctrine_Collection $attribute_value
 * 
 * @method integer             getAttributeDefId()   Returns the current record's "attribute_def_id" value
 * @method string              getValue()            Returns the current record's "value" value
 * @method attribute_def       getAttributeDef()     Returns the current record's "attribute_def" value
 * @method Doctrine_Collection getAttributeValue()   Returns the current record's "attribute_value" collection
 * @method attribute_def_value setAttributeDefId()   Sets the current record's "attribute_def_id" value
 * @method attribute_def_value setValue()            Sets the current record's "value" value
 * @method attribute_def_value setAttributeDef()     Sets the current record's "attribute_def" value
 * @method attribute_def_value setAttributeValue()   Sets the current record's "attribute_value" collection
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseattribute_def_value extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attribute_def_value');
        $this->hasColumn('attribute_def_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('attribute_def', array(
             'local' => 'attribute_def_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('attribute_value', array(
             'local' => 'id',
             'foreign' => 'attribute_def_value_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'value',
             ),
             ));
        $this->actAs($i18n0);
    }
}