<?php

/**
 * Basemodule_cms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $route_name
 * @property integer $module_group_id
 * @property boolean $hidden
 * @property module_group $module_group
 * @property Doctrine_Collection $permission
 * @property Doctrine_Collection $media_size
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getRouteName()       Returns the current record's "route_name" value
 * @method integer             getModuleGroupId()   Returns the current record's "module_group_id" value
 * @method boolean             getHidden()          Returns the current record's "hidden" value
 * @method module_group        getModuleGroup()     Returns the current record's "module_group" value
 * @method Doctrine_Collection getPermission()      Returns the current record's "permission" collection
 * @method Doctrine_Collection getMediaSize()       Returns the current record's "media_size" collection
 * @method module_cms          setName()            Sets the current record's "name" value
 * @method module_cms          setRouteName()       Sets the current record's "route_name" value
 * @method module_cms          setModuleGroupId()   Sets the current record's "module_group_id" value
 * @method module_cms          setHidden()          Sets the current record's "hidden" value
 * @method module_cms          setModuleGroup()     Sets the current record's "module_group" value
 * @method module_cms          setPermission()      Sets the current record's "permission" collection
 * @method module_cms          setMediaSize()       Sets the current record's "media_size" collection
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemodule_cms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('module_cms');
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('route_name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('module_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('hidden', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('module_group', array(
             'local' => 'module_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('sfGuardPermission as permission', array(
             'refClass' => 'module_permission',
             'local' => 'module_id',
             'foreign' => 'permission_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('media_size', array(
             'local' => 'id',
             'foreign' => 'module_cms_id'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             ));
        $this->actAs($sortable0);
    }
}