<?php

/**
 * Baseproduct_categories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $parent_id
 * @property boolean $hidden
 * @property product_categories $parent
 * @property Doctrine_Collection $product
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method integer             getParentId()           Returns the current record's "parent_id" value
 * @method boolean             getHidden()             Returns the current record's "hidden" value
 * @method product_categories  getParent()             Returns the current record's "parent" value
 * @method Doctrine_Collection getProductCategories()  Returns the current record's "product_categories" collection
 * @method Doctrine_Collection getProduct()            Returns the current record's "product" collection
 * @method product_categories  setName()               Sets the current record's "name" value
 * @method product_categories  setParentId()           Sets the current record's "parent_id" value
 * @method product_categories  setHidden()             Sets the current record's "hidden" value
 * @method product_categories  setParent()             Sets the current record's "parent" value
 * @method product_categories  setProductCategories()  Sets the current record's "product_categories" collection
 * @method product_categories  setProduct()            Sets the current record's "product" collection_categories
 * @property Doctrine_Collection $product
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method integer             getParentId()           Returns the current record's "parent_id" value
 * @method boolean             getHidden()             Returns the current record's "hidden" value
 * @method product_categories  getParent()             Returns the current record's "parent" value
 * @method Doctrine_Collection getProductCategories()  Returns the current record's "product_categories" collection
 * @method Doctrine_Collection getProduct()            Returns the current record's "product" collection
 * @method product_categories  setName()               Sets the current record's "name" value
 * @method product_categories  setParentId()           Sets the current record's "parent_id" value
 * @method product_categories  setHidden()             Sets the current record's "hidden" value
 * @method product_categories  setParent()             Sets the current record's "parent" value
 * @method product_categories  setProductCategories()  Sets the current record's "product_categories" collection
 * @method product_categories  setProduct()            Sets the current record's "product" collection
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseproduct_categories extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_categories');
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('hidden', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('product_categories as parent', array(
             'local' => 'parent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('product_categories', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('product', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'parent_id',
             ),
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($sortable0);
        $this->actAs($i18n0);
    }
}