<?php

/**
 * Baselang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $flag
 * @property string $slug
 * @property boolean $hidden
 * 
 * @method string  getName()   Returns the current record's "name" value
 * @method string  getFlag()   Returns the current record's "flag" value
 * @method string  getSlug()   Returns the current record's "slug" value
 * @method boolean getHidden() Returns the current record's "hidden" value
 * @method lang    setName()   Sets the current record's "name" value
 * @method lang    setFlag()   Sets the current record's "flag" value
 * @method lang    setSlug()   Sets the current record's "slug" value
 * @method lang    setHidden() Sets the current record's "hidden" value
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baselang extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lang');
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('flag', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('slug', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('hidden', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sortable0 = new Doctrine_Template_Sortable(array(
             ));
        $this->actAs($sortable0);
    }
}