<?php

/**
 * Baseattribute_value
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $attribute_def_id
 * @property integer $attribute_def_value_id
 * @property integer $attribute_type_id
 * @property integer $product_id
 * @property string $value
 * @property attribute_def $attribute_def
 * @property attribute_def_value $attribute_def_value
 * @property attribute_type $attribute_type
 * @property product $product
 * 
 * @method integer             getAttributeDefId()         Returns the current record's "attribute_def_id" value
 * @method integer             getAttributeDefValueId()    Returns the current record's "attribute_def_value_id" value
 * @method integer             getAttributeTypeId()        Returns the current record's "attribute_type_id" value
 * @method integer             getProductId()              Returns the current record's "product_id" value
 * @method string              getValue()                  Returns the current record's "value" value
 * @method attribute_def       getAttributeDef()           Returns the current record's "attribute_def" value
 * @method attribute_def_value getAttributeDefValue()      Returns the current record's "attribute_def_value" value
 * @method attribute_type      getAttributeType()          Returns the current record's "attribute_type" value
 * @method product             getProduct()                Returns the current record's "product" value
 * @method attribute_value     setAttributeDefId()         Sets the current record's "attribute_def_id" value
 * @method attribute_value     setAttributeDefValueId()    Sets the current record's "attribute_def_value_id" value
 * @method attribute_value     setAttributeTypeId()        Sets the current record's "attribute_type_id" value
 * @method attribute_value     setProductId()              Sets the current record's "product_id" value
 * @method attribute_value     setValue()                  Sets the current record's "value" value
 * @method attribute_value     setAttributeDef()           Sets the current record's "attribute_def" value
 * @method attribute_value     setAttributeDefValue()      Sets the current record's "attribute_def_value" value
 * @method attribute_value     setAttributeType()          Sets the current record's "attribute_type" value
 * @method attribute_value     setProduct()                Sets the current record's "product" value
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseattribute_value extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attribute_value');
        $this->hasColumn('attribute_def_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('attribute_def_value_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('attribute_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('attribute_def', array(
             'local' => 'attribute_def_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('attribute_def_value', array(
             'local' => 'attribute_def_value_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('attribute_type', array(
             'local' => 'attribute_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'value',
             ),
             ));
        $this->actAs($i18n0);
    }
}