<?php

/**
 * Basemodule_group_permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $module_group_id
 * @property integer $permission_id
 * @property module_group $module_group
 * @property sfGuardPermission $permission
 * 
 * @method integer                 getModuleGroupId()   Returns the current record's "module_group_id" value
 * @method integer                 getPermissionId()    Returns the current record's "permission_id" value
 * @method module_group            getModuleGroup()     Returns the current record's "module_group" value
 * @method sfGuardPermission       getPermission()      Returns the current record's "permission" value
 * @method module_group_permission setModuleGroupId()   Sets the current record's "module_group_id" value
 * @method module_group_permission setPermissionId()    Sets the current record's "permission_id" value
 * @method module_group_permission setModuleGroup()     Sets the current record's "module_group" value
 * @method module_group_permission setPermission()      Sets the current record's "permission" value
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemodule_group_permission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('module_group_permission');
        $this->hasColumn('module_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('module_group', array(
             'local' => 'module_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardPermission as permission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}