<?php

/**
 * Basenewsletter_address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property string $hash
 * @property boolean $confirm
 * 
 * @method string             getEmail()   Returns the current record's "email" value
 * @method string             getHash()    Returns the current record's "hash" value
 * @method boolean            getConfirm() Returns the current record's "confirm" value
 * @method newsletter_address setEmail()   Sets the current record's "email" value
 * @method newsletter_address setHash()    Sets the current record's "hash" value
 * @method newsletter_address setConfirm() Sets the current record's "confirm" value
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basenewsletter_address extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter_address');
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('hash', 'string', 40, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 40,
             ));
        $this->hasColumn('confirm', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}