<?php

/**
 * Basemodule_permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $module_id
 * @property integer $permission_id
 * @property sfGuardPermission $permission
 * 
 * @method integer           getModuleId()      Returns the current record's "module_id" value
 * @method integer           getPermissionId()  Returns the current record's "permission_id" value
 * @method sfGuardPermission getPermission()    Returns the current record's "permission" value
 * @method module_permission setModuleId()      Sets the current record's "module_id" value
 * @method module_permission setPermissionId()  Sets the current record's "permission_id" value
 * @method module_permission setPermission()    Sets the current record's "permission" value
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemodule_permission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('module_permission');
        $this->hasColumn('module_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardPermission as permission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}