# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [cms/backend.css, /sfDoctrinePlugin/css/default.css, /sfDoctrinePlugin/css/global.css, /csDoctrineActAsSortablePlugin/css/sortable.css]

  javascripts:    [jquery.js, cms/main.js, tiny_mce/tiny_mce, tiny_mce/plugins/tinybrowser/tb_tinymce.js.php]

  has_layout:     true
  layout:         layout
