<?php

/**
 * articleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class articleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object articleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('article');
    }
    
    public static function getArticleForPager(){
      return Doctrine_Query::create()
              ->from('article')
              ->where('hidden = ?', 0)
              ->andWhere('date_from < ?', date('Y-m-d'))
              ->orderBy('date_from DESC');
    }
    
    public static function prevArticle($article){
      return Doctrine_Query::create()
              ->from('article')
              ->where('hidden = ?', 0)
              ->andWhere('date_from < ?', $article->getDateFrom())
              ->orderBy('date_from DESC')
              ->limit(1)
              ->execute()->getFirst();
    }
    
    public static function nextArticle($article){
      return Doctrine_Query::create()
              ->from('article')
              ->where('hidden = ?', 0)
              ->andWhere('date_from > ?', $article->getDateFrom())
              ->orderBy('date_from DESC')
              ->limit(1)
              ->execute()->getFirst();
    }
}