<?php

/**
 * article_categoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class article_categoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object article_categoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('article_category');
    }
}