<?php

/**
 * attachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class attachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object attachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('attachment');
    }
}