<?php

/**
 * attribute_typeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class attribute_typeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object attribute_typeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('attribute_type');
    }
}