<?php

/**
 * attribute_def_valueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class attribute_def_valueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object attribute_def_valueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('attribute_def_value');
    }
    
    /**
     * Pobiera wartosci zdefiniowanego atrybutu
     * @param type $id id atrybutu
     * @return Doctrine_Collection
     */
    public static function getAttributeDefValues($id){
      return Doctrine_Query::create()
              ->from('attribute_def_value adv')
              ->leftJoin('adv.Translation t')
              ->where('adv.attribute_def_id = ?', $id)
              ->execute();
    }
}