<?php

/**
 * attribute_defTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class attribute_defTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object attribute_defTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('attribute_def');
    }
    
    /**
     * Pobiera ids definicji atrybutów dla kategorii produktów
     */
    public static function getCategoriesAttributesIds( $categorieIds ){
      $attributes = Doctrine_Query::create()
              ->from('attribute_def')
              ->where('module = ?', 'product_categories')
              ->andWhereIn('parent_id', $categorieIds)
              ->execute();
      
      if( $attributes ){
        $attribteIds = array();
        foreach ($attributes as $attribute){
          $attribteIds[] = $attribute->getId();
        }
        return $attribteIds;
      }
      else{
        return false;
      }
    }
    
    /**
     * Pobiera atrybuty o zadanych ids
     * @param integer $ids ids atrybutów
     * @return Doctrine_Collection
     */
    public static function getAttributeByIds( $ids ){
      return Doctrine_Query::create()
              ->from('attribute_def')
              ->whereIn('id', $ids)
              ->execute();
    }
    
    
    /**
     * Pobiera atrybut o zadanym id
     * @param integer $id id attrybutu
     * @return Doctrine_Collection
     */
    public static function getAttributeById($id){
      return Doctrine_Query::create()
              ->from('attribute_def ad')
              ->leftJoin('ad.Translation t')
              ->where('ad.id = ?', $id)
              ->execute()
              ->getFirst();
    }
}