<?php

/**
 * attribute_def_value
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class attribute_def_value extends Baseattribute_def_value
{

}