<?php

/**
 * gallery_1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class gallery_1Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object gallery_1Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('gallery_1');
    }
}