<?php

/**
 * gallery_1
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class gallery_1 extends Basegallery_1
{

}