<?php

/**
 * lang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI tomasz.rogalski@huevo.pl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class lang extends Baselang {

  public function getSlug2() {
    $langSlug = substr($this->getSlug(), 0, 2);
    return strtoupper($langSlug);
  }

}