<?php

/**
 * mail_dataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mail_dataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mail_dataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mail_data');
    }
}