<?php

/**
 * media_sizeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class media_sizeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object media_sizeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('media_size');
    }
    
    public static function getSizeOfModule($moduleName){
      return Doctrine_Query::create()
              ->from('media_size ms')
              ->leftJoin('ms.module_cms mc')              
              ->where('mc.route_name = ?', $moduleName)
              ->execute()->getFirst();
    }
}