<?php

/**
 * mediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mediaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object mediaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('media');
    }

    public static function getMainMedia($module, $parentId) {
        $q = Doctrine_Query::create()
                        ->from('media')
                        ->where('module = ?', $module)
                        ->andWhere('parent_id = ?', $parentId)
                        ->andWhere('main = ?', 1)
                        ->orderBy('position ASC')
                        ->execute()->getFirst();
        if ($q) {
            return $q;
        } else {
            return Doctrine_Query::create()
                            ->from('media')
                            ->where('module = ?', $module)
                            ->andWhere('parent_id = ?', $parentId)
                            ->orderBy('position ASC')
                            ->execute()->getFirst();
        }
    }

    public static function getGallery($module, $parentId) {
        return Doctrine_Query::create()
                        ->from('media')
                        ->where('module = ?', $module)
                        ->andWhere('parent_id = ?', $parentId)
                        ->orderBy('position ASC')
                        ->execute();
    }

    public static function getMediaForPager($mediaIds) {
        $media = Doctrine_Query::create()
                ->from('media m')
                ->leftJoin('m.Translation mt');
        if (count($mediaIds)) {
            $media->whereIn('m.id', $mediaIds);
        }
        $media->orderBy('m.id ASC');
        return $media;
    }

}
