<?php

/**
 * meta_tagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class meta_tagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object meta_tagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('meta_tag');
    }
}