<?php

/**
 * module_groupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class module_groupTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object module_groupTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('module_group');
  }

  public static function getModuleGroups() {
    return Doctrine_Query::create()
                    ->from('module_group')
                    ->andWhere('hidden = ?', 0)
                    ->execute();
  }

}