<?php

/**
 * module_permissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class module_permissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object module_permissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('module_permission');
    }
    
    public static function getModulePermission($moduleId){
      return Doctrine_Query::create()
              ->from('module_permission mp')
              ->leftJoin('mp.permission p')
              ->where('mp.module_id = ?', $moduleId)
              ->execute();
    }
}