<?php

/**
 * module_cmsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class module_cmsTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object module_cmsTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('module_cms');
  }

  public static function getModulesByModuleGroupId($groupId) {
    return Doctrine_Query::create()
                    ->from('module_cms')
                    ->andWhere('hidden = ?', 0)
                    ->andWhere('module_group_id = ?', $groupId)
                    ->execute();
  }

  public static function getModulePermission($moduleRoutName) {
    $module = Doctrine_Query::create()
                    ->from('module_cms')
                    ->andWhere('route_name = ?', $moduleRoutName)
                    ->execute()->getFirst();

    if ($module) {
      $modulePermission = module_permissionTable::getModulePermission($module->getId());
      if ($modulePermission->count()) {
        return $modulePermission;
      } else {
        return false;
      }
    } else {
      return false;
    }
  }
  
  public static function getModuleCMS() {
    return Doctrine_Query::create()
                    ->from('module_cms')
                    ->andWhere('hidden = ?', 0)
                    ->execute();
  }

}