<?php

/**
 * newsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class newsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object newsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('news');
    }
    
    public static function getLastNews(){
      return Doctrine_Query::create()
              ->from('news')
              ->where('hidden = ?', 0)
              ->orderBy('date_from DESC')
              ->execute()->getFirst();
    }
    
    public static function getNewsForPager(){
      return Doctrine_Query::create()
              ->from('news')
              ->where('hidden = ?', 0)
              ->andWhere('date_from < ?', date('Y-m-d'))
              ->orderBy('date_from DESC');
    }
    
    public static function prevNews($new){
      return Doctrine_Query::create()
              ->from('news')
              ->where('hidden = ?', 0)
              ->andWhere('date_from < ?', $new->getDateFrom())
              ->orderBy('date_from DESC')
              ->limit(1)
              ->execute()->getFirst();
    }
    
    public static function nextNews($new){
      return Doctrine_Query::create()
              ->from('news')
              ->where('hidden = ?', 0)
              ->andWhere('date_from > ?', $new->getDateFrom())
              ->orderBy('date_from DESC')
              ->limit(1)
              ->execute()->getFirst();
    }
}