<?php

/**
 * newsletter_addressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class newsletter_addressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object newsletter_addressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('newsletter_address');
    }
    
    public static function deleteAddress($email){
      return Doctrine_Query::create()
              ->delete('newsletter_address')
              ->where('email = ?', $email)
              ->execute();
    }
}