<?php

/**
 * pageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('page');
    }
    
    public static function getMenuHeader(){
      return Doctrine_Query::create()
              ->from('page')
              ->andWhere('parent_id IS ?', NULL)
              ->andWhere('not_in_menu = ?', 0)
              ->andWhere('hidden = ?', 0)
              ->orderBy('position ASC')
              ->execute();
    }
    
    public static function getMenuFooter(){
      return Doctrine_Query::create()
              ->from('page')
              ->andWhere('parent_id IS NULL OR route_hash = "offer_equipment"')              
              ->andWhere('not_in_menu = ?', 0)
              ->andWhere('hidden = ?', 0)
              ->orderBy('position ASC')
              ->execute();
    }
    
    public static function getFirstPage(){
      return Doctrine_Query::create()
              ->from('page')
              ->andWhere('parent_id IS ?', NULL)
              ->andWhere('hidden = ?', 0)
              ->orderBy('position ASC')
              ->execute()->getFirst();
    }
    
    public static function getSubPage($page){
      return Doctrine_Query::create()
              ->from('page')
              ->andWhere('parent_id = ?', $page->getId())
              ->andWhere('hidden = ?', 0)
              ->orderBy('position ASC')
              ->execute();
    }
    
    public static function getPageByRouteHash($route){
      return Doctrine_Query::create()
              ->from('page')
              ->where('hidden = ?', 0)
              ->andWhere('route_hash = ?', $route)
              ->execute()->getFirst();
    }
}