<?php

/**
 * product_categoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class product_categoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object product_categoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('product_categories');
    }
    
    public static function getParentsCategoryProduct( $product ){
      $parents = array();
      
      $category = Doctrine_Query::create()
              ->from('product_categories')
              ->where('id = ?', $product->getCategoryId() )
              ->fetchOne();
      
      $parents[] = $category->getId();
      if( $category->getParentId() ){
        $parent = self::getParentsCategory( $category->getParentId(), $parents );
        if( $parent ){
          $parents[] = $parent;
        }
      }
      
      if ( count($parents) ){
        return $parents;
      }
      else{
        return false;
      }
    }
    
    private static function getParentsCategory( $parentId, $parents ){
      $category =  Doctrine_Query::create()
              ->from('product_categories')
              ->where('id = ?', $parentId)
              ->fetchOne();
      
      if( $category->getParentId() ){
        $parents[] = $category->getId();
        $parent = self::getParentsCategory( $category->getParentId(), $parents );
        if( $parent ){
          $parents[] = $parent;
        }
      }
      else{
        if( $category->getId() ) return $category->getId();
      }
      
    }
    
    public static function getCategories(){
      return Doctrine_Query::create()
              ->from('product_categories')
              ->where('parent_id IS NULL')
              ->andWhere('hidden = 0')
              ->orderBy('position ASC')
              ->execute();
    }
    
    public static function getFirstCategory(){
      return Doctrine_Query::create()
              ->from('product_categories')
              ->where('parent_id IS NULL')
              ->orderBy('position ASC')
              ->execute()->getFirst();
    }
}