<?php

/**
 * textTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class textTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object textTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('text');
    }
    
    public static function getPageContext( $pageId ){
      return Doctrine_Query::create()
              ->from('text')
              ->where('module = ?', 'page')
              ->andWhere('parent_id = ?', $pageId)
              ->andWhere('hidden = ?', 0)
              ->execute();
    }
}