<?php

/**
 * BasesfGuardPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $sfGuardGroupPermission
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $module_cms
 * @property Doctrine_Collection $module_group
 * @property Doctrine_Collection $module_group_permission
 * @property Doctrine_Collection $module_permission
 * 
 * @method string              getName()                    Returns the current record's "name" value
 * @method string              getDescription()             Returns the current record's "description" value
 * @method Doctrine_Collection getGroups()                  Returns the current record's "Groups" collection
 * @method Doctrine_Collection getSfGuardGroupPermission()  Returns the current record's "sfGuardGroupPermission" collection
 * @method Doctrine_Collection getUsers()                   Returns the current record's "Users" collection
 * @method Doctrine_Collection getSfGuardUserPermission()   Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection getModuleCms()               Returns the current record's "module_cms" collection
 * @method Doctrine_Collection getModuleGroup()             Returns the current record's "module_group" collection
 * @method Doctrine_Collection getModuleGroupPermission()   Returns the current record's "module_group_permission" collection
 * @method Doctrine_Collection getModulePermission()        Returns the current record's "module_permission" collection
 * @method sfGuardPermission   setName()                    Sets the current record's "name" value
 * @method sfGuardPermission   setDescription()             Sets the current record's "description" value
 * @method sfGuardPermission   setGroups()                  Sets the current record's "Groups" collection
 * @method sfGuardPermission   setSfGuardGroupPermission()  Sets the current record's "sfGuardGroupPermission" collection
 * @method sfGuardPermission   setUsers()                   Sets the current record's "Users" collection
 * @method sfGuardPermission   setSfGuardUserPermission()   Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardPermission   setModuleCms()               Sets the current record's "module_cms" collection
 * @method sfGuardPermission   setModuleGroup()             Sets the current record's "module_group" collection
 * @method sfGuardPermission   setModuleGroupPermission()   Sets the current record's "module_group_permission" collection
 * @method sfGuardPermission   setModulePermission()        Sets the current record's "module_permission" collection
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_permission');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardGroupPermission',
             'local' => 'permission_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardGroupPermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'permission_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $this->hasMany('module_cms', array(
             'refClass' => 'module_permission',
             'local' => 'permission_id',
             'foreign' => 'module_id'));

        $this->hasMany('module_group', array(
             'refClass' => 'module_group_permission',
             'local' => 'permission_id',
             'foreign' => 'module_group_id'));

        $this->hasMany('module_group_permission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $this->hasMany('module_permission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}